# Generated by Django 4.0.5 on 2022-07-11 01:39

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyviews',
            options={'verbose_name': 'Total Views on Property', 'verbose_name_plural': 'Total Property Views'},
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Bathrooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(default=1, verbose_name='Bedrooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(default='Nairobi', max_length=180, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=django_countries.fields.CountryField(default='KE', max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(default='Default description...update me please....', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='plot_area',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Plot Area(m^2)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='postal_code',
            field=models.CharField(default='140', max_length=100, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_number',
            field=models.IntegerField(default=112, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Property Number'),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='street_address',
            field=models.CharField(default='KG8 Avenue', max_length=150, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='property',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent_buyer', to=settings.AUTH_USER_MODEL, verbose_name='Agent,Seller or Buyer'),
        ),
        migrations.AlterField(
            model_name='property',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Total Views'),
        ),
        migrations.AlterField(
            model_name='propertyviews',
            name='ip',
            field=models.CharField(max_length=250, verbose_name='IP Address'),
        ),
    ]
