name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  BUILD:
 
    runs-on: ubuntu-latest
    env:         
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: ${{ secrets.DEBUG }}
        ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
        PG_ENGINE: ${{ secrets.PG_ENGINE }}
        PG_DB: ${{ secrets.PG_DB }}
        PG_USER: ${{ secrets.PG_USER }}
        PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
        PG_HOST: ${{ secrets.PG_HOST }}
        PG_PORT: ${{ secrets.PG_PORT }}
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
        EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
        EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
        EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
        DOMAIN: ${{ secrets.DOMAIN }}
 
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker compose up --build -d --remove-orphans
  
 
