name: Docker-Build-(dev)

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  docker-build-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          envkey_DEBUG: ${{ secrets.DEBUG }}
          envkey_ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
          envkey_PG_ENGINE: ${{ secrets.PG_ENGINE }}
          envkey_PG_DB: ${{ secrets.PG_DB }}
          envkey_PG_USER: ${{ secrets.PG_USER }}
          envkey_PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          envkey_PG_HOST: ${{ secrets.PG_HOST }}
          envkey_PG_PORT: ${{ secrets.PG_PORT }}
          envkey_SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          envkey_EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          envkey_EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          envkey_EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          envkey_EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          envkey_DOMAIN: ${{ secrets.DOMAIN }}
          envkey_CELERY_BACKEND: ${{secrets.CELERY_BACKEND}}
          envkey_CELERY_BROKER: ${{secrets.CELERY_BROKER}}
          file_name: .env
          fail_on_empty: false
      - name: going to client folder
        run: ls -l
      - name: Make envfile in client folder
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_WDS_SOCKET_PORT: ${{ secrets.WDS_SOCKET_PORT }}
          file_name: .env
          fail_on_empty: false
      - name: build docker
        #run: docker compose up --build -d --remove-orphans
