name: Docker-Build-(dev)

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  docker-build-dev:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Make envfile
        run: |
          pwd
          touch .env
          echo SECRET_KEY=${{ secrets.SECRET_KEY }} >> .env
          echo DEBUG=${{ secrets.DEBUG }}
          echo ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}
          echo PG_ENGINE=${{ secrets.PG_ENGINE }}
          echo PG_DB=${{ secrets.PG_DB }}
          echo PG_USER=${{ secrets.PG_USER }}
          echo PG_PASSWORD=${{ secrets.PG_PASSWORD }}
          echo PG_HOST=${{ secrets.PG_HOST }}
          echo PG_PORT=${{ secrets.PG_PORT }}
          echo SIGNING_KEY=${{ secrets.SIGNING_KEY }}
          echo EMAIL_HOST=${{ secrets.EMAIL_HOST }}
          echo EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}
          echo EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}
          echo EMAIL_PORT=${{ secrets.EMAIL_PORT }}
          echo DOMAIN=${{ secrets.DOMAIN }}
          echo CELERY_BACKEND=${{secrets.CELERY_BACKEND}}
          echo CELERY_BROKER=${{secrets.CELERY_BROKER}}
          cat .env
          pwd
          ls -l 
      - name: Make envfile in client folder
        run: |
          pwd
          cd ./client
          ls -l 
          touch .env
          echo WDS_SOCKET_PORT=${{ secrets.WDS_SOCKET_PORT }} >> .env
          cat .env
          pwd
          ls -l 
     # - name: build docker
        #run: docker compose up --build -d --remove-orphans
